// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */

// // @ts-check

export default {
  mySidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
  ],
};


// /*
// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// export default {
//   mySidebar: [
//     "how-to-install",
//   ],
// }

//   /*
//   tutorialSidebar: [
//     "how-to-install",
//     // {
//     //   type: "category",
//     //   label: "Deploying Disco Projects",
//     //   collapsible: true,
//     //   collapsed: false,
//     //   items: [
//     //     "deploying-projects/deploying-a-static-site",
//     //     "deploying-projects/deploying-a-flask-site",
//     //   ],
//     // },
//   ],
// */
//   // But you can create a sidebar manually
//   /*
//     tutorialSidebar: [
//       "how-to-install",
//       {
//         type: 'category',
//         label: 'Tutorial',
//         items: ['tutorial-basics/create-a-document'],
//       },
//     ],
//     */
// };

// export default sidebars;
